name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myrshrma1/wisecow:latest .

    - name: Push Docker image
      run: docker push myrshrma1/wisecow:latest

    - name: Save KUBECONFIG to file
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
        kubectl apply -f wisecow-ingress.yaml
