name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myrshrma1/wisecow:latest .

    - name: Push Docker image
      run: docker push myrshrma1/wisecow:latest

    - name: Save kubeconfig to file
      run: echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig

    - name: Debug kubeconfig and network
      run: |
        export KUBECONFIG=/tmp/kubeconfig
        kubectl config view
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=/tmp/kubeconfig
        kubectl apply --validate=false -f wisecow-deployment.yaml
        kubectl apply --validate=false -f wisecow-service.yaml
        kubectl apply --validate=false -f wisecow-ingress.yaml
      env:
        KUBECONFIG: /tmp/kubeconfig
