name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myrshrma1/wisecow:latest .

    - name: Push Docker image
      run: docker push myrshrma1/wisecow:latest

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Set up KUBECONFIG
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Verify KUBECONFIG
      run: cat $HOME/.kube/config

    - name: Check Kubernetes Cluster
      run: kubectl cluster-info
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
        kubectl apply -f wisecow-ingress.yaml
      env:
        KUBECONFIG: $HOME/.kube/config
