name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myrshrma1/wisecow:latest .

    - name: Push Docker image
      run: docker push myrshrma1/wisecow:latest

    - name: Create .kube directory
      run: mkdir -p $HOME/.kube

    - name: Print Raw KUBECONFIG Content
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d

    - name: Set up KUBECONFIG
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Validate KUBECONFIG
      run: |
        kubectl config view
        kubectl cluster-info
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Debug Kubernetes Connectivity
      run: |
        kubectl version
        kubectl get nodes
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yaml --validate=false
        kubectl apply -f wisecow-service.yaml --validate=false
        kubectl apply -f wisecow-ingress.yaml --validate=false
      env:
        KUBECONFIG: $HOME/.kube/config
